"""Columns removed during preprocessing (config.prep.COLS_TO_DROP).

Curation list for the prediction tables. Grouped by reason below. NOTE: the
developability/energy group is retained by data_prep (category-aware drop) for
filtering; every other group is dropped. Membership is unchanged by the grouping.
"""

COLS_TO_DROP = [
    # Non-metric columns (labels, file paths) -- never features.
    "binding",
    "interface",
    "chai_unconstrained_model_path",
    "chai_constrained_model_path",
    "boltz_free_model_path",
    "boltz_template_model_path",

    # Rank / ranking-score columns (ordinal artefacts, not comparable metrics).
    "af3_rank",
    "af3_ranking_score",
    "af3_rank0_masif",
    "cf_rank",
    "cf_rank0_masif",

    # MPNN sequence metrics (confidence / negative log-likelihood) -- dropped from the analysed set.
    "cf_mpnn_confidence",
    "cf_mpnn_nll",
    "cf_mpnn_nll_a",
    "cf_mpnn_nll_b",
    "af3_mpnn_confidence",
    "af3_mpnn_nll",
    "af3_mpnn_nll_a",
    "af3_mpnn_nll_b",
    "esmfold2_mpnn_confidence",
    "esmfold2_mpnn_nll",
    "esmfold2_mpnn_nll_a",
    "esmfold2_mpnn_nll_b",
    "chai_unconstrained_mpnn_confidence",
    "chai_unconstrained_mpnn_nll",
    "chai_unconstrained_mpnn_nll_a",
    "chai_unconstrained_mpnn_nll_b",
    "chai_constrained_mpnn_confidence",
    "chai_constrained_mpnn_nll",
    "chai_constrained_mpnn_nll_a",
    "chai_constrained_mpnn_nll_b",
    "boltz_free_mpnn_confidence",
    "boltz_free_mpnn_nll",
    "boltz_free_mpnn_nll_a",
    "boltz_free_mpnn_nll_b",
    "boltz_template_mpnn_confidence",
    "boltz_template_mpnn_nll",
    "boltz_template_mpnn_nll_a",
    "boltz_template_mpnn_nll_b",

    # ESMFold (v1) columns -- this model is excluded from the analysis.
    "esmfold_pae",
    "esmfold_plddt",
    "esmfold_ptm",
    "esmfold_ipae",
    "esmfold_iplddt",
    "esmfold_mpnn_confidence",
    "esmfold_mpnn_nll",
    "esmfold_mpnn_nll_a",
    "esmfold_mpnn_nll_b",

    # Chai-1 duplicate confidence/interface columns not used in the analysed set.
    "chai_unconstrained_score",
    "chai_unconstrained_aggregate_score",
    "chai_unconstrained_ptm",
    "chai_unconstrained_per_chain_ptm",
    "chai_unconstrained_iptm",
    "chai_unconstrained_per_chain_pair_iptm",
    "chai_unconstrained_interface_iptm",
    "chai_unconstrained_ipsae",
    "chai_unconstrained_pdockq2",
    "chai_unconstrained_lis",
    "chai_constrained_score",
    "chai_constrained_aggregate_score",
    "chai_constrained_ptm",
    "chai_constrained_per_chain_ptm",
    "chai_constrained_iptm",
    "chai_constrained_interface_iptm",
    "chai_constrained_per_chain_pair_iptm",
    "chai_constrained_ipsae",
    "chai_constrained_pdockq2",
    "chai_constrained_lis",
    "chai_unconstrained_pdockq",
    "chai_constrained_pdockq",

    # pDockQ (v1) columns -- pdockq2 is used instead.
    "af3_pdockq",
    "cf_pdockq",
    "boltz_free_pdockq",
    "boltz_template_pdockq",

    # Developability & energy metrics -- KEPT through preprocessing by data_prep's
    # category-aware drop (used for filtering, energy mainly for nanobodies); listed here so
    # they are excluded when this list IS applied, but data_prep re-includes them.
    "cf_esm3dg_dg",
    "cf_esm3dg_dg_a",
    "cf_esm3dg_dg_b",
    "cf_esm3dg_dg_std",
    "af3_esm3dg_dg",
    "af3_esm3dg_dg_a",
    "af3_esm3dg_dg_b",
    "af3_esm3dg_dg_std",
    "esmfold_esm3dg_dg",
    "esmfold_esm3dg_dg_a",
    "esmfold_esm3dg_dg_b",
    "esmfold_esm3dg_dg_std",
    "esmfold2_esm3dg_dg",
    "esmfold2_esm3dg_dg_a",
    "esmfold2_esm3dg_dg_b",
    "esmfold2_esm3dg_dg_std",
    "chai_unconstrained_esm3dg_dg",
    "chai_unconstrained_esm3dg_dg_a",
    "chai_unconstrained_esm3dg_dg_b",
    "chai_unconstrained_esm3dg_dg_std",
    "chai_constrained_esm3dg_dg",
    "chai_constrained_esm3dg_dg_a",
    "chai_constrained_esm3dg_dg_b",
    "chai_constrained_esm3dg_dg_std",
    "boltz_free_esm3dg_dg",
    "boltz_free_esm3dg_dg_a",
    "boltz_free_esm3dg_dg_b",
    "boltz_free_esm3dg_dg_std",
    "boltz_template_esm3dg_dg",
    "boltz_template_esm3dg_dg_a",
    "boltz_template_esm3dg_dg_b",
    "boltz_template_esm3dg_dg_std",
    "af3_interface_dG",
    "af3_interface_dG_SASA_ratio",
    "af3_pyros_binder_score",
    "cf_interface_dG",
    "cf_interface_dG_SASA_ratio",
    "cf_pyros_binder_score",
    "af3_surface_hydrophobicity",
    "af3_interface_sc",
    "af3_interface_packstat",
    "af3_interface_delta_unsat_hbonds",
    "af3_interface_nres",
    "af3_interface_hydrophobicity",
    "cf_surface_hydrophobicity",
    "cf_interface_sc",
    "cf_interface_packstat",
    "cf_interface_delta_unsat_hbonds",
    "cf_interface_nres",
    "cf_interface_hydrophobicity",
    "af3_sap_score",
    "af3_hydrophobic_sasa",
    "af3_net_charge",
    "af3_sap_score_complex",
    "af3_dsap",
    "cf_sap_score",
    "cf_hydrophobic_sasa",
    "cf_net_charge",
    "cf_sap_score_complex",
    "cf_dsap",

    # Other curated-out columns.
    "af3_interface_dSASA",
    "af3_interface_interface_hbonds",
    "cf_interface_dSASA",
    "cf_interface_interface_hbonds",
    "af3_sap_score_unbound_cframe",
    "cf_sap_score_unbound_cframe",

]
